#ifndef IR0_LEXER_H_
#define IR0_LEXER_H_

#include <base.h>
#include <stdint.h>


enum
{
    TOKEN_KEYWORD = 0x10000,

    TOKEN_KEYWORD_MOV,
    TOKEN_KEYWORD_LDR,
    TOKEN_KEYWORD_STR,

    TOKEN_KEYWORD_ADD,
    TOKEN_KEYWORD_SUB,
    TOKEN_KEYWORD_MUL,
    TOKEN_KEYWORD_AND,
    TOKEN_KEYWORD_OR,
    TOKEN_KEYWORD_XOR,
    TOKEN_KEYWORD_NOT,
    TOKEN_KEYWORD_SHR,
    TOKEN_KEYWORD_SHL,

    TOKEN_KEYWORD_CMP,
    TOKEN_KEYWORD_JMP,
    TOKEN_KEYWORD_JE,
    TOKEN_KEYWORD_JNE,
    TOKEN_KEYWORD_JL,
    TOKEN_KEYWORD_JLE,
    TOKEN_KEYWORD_JG,
    TOKEN_KEYWORD_JGE,

    TOKEN_KEYWORD_SETE,
    TOKEN_KEYWORD_SETNE,

    TOKEN_KEYWORD_CALL,
    TOKEN_KEYWORD_RET,
    TOKEN_KEYWORD_SYSCALL,
};


#endif /* IR0_LEXER_H_ */
